/*******************************************************
* Fixed.frag Fixed Function Equivalent Fragment Shader *
*   Automatically Generated by 3Dlabs GLSL ShaderGen   *
*             http://developer.3dlabs.com              *
*******************************************************/
uniform sampler2D texUnit0;
uniform sampler2D texUnit1;
uniform sampler2D texUnit2;

void main (void) 
{
    vec4 color;

    color = gl_Color;

    color *= texture2D(texUnit0, gl_TexCoord[0].xy);

    vec4 texture1Arg0 = texture2D(texUnit1, gl_TexCoord[1].xy);
    vec4 texUnit1Arg0 = texture1Arg0;
    vec4 texUnit1Arg1 = color;
    color = clamp(2.0 * texUnit1Arg0 * texUnit1Arg1, 0.0, 1.0);
    color *= texture2D(texUnit2, gl_TexCoord[2].xy);

    color += gl_SecondaryColor;
    color = clamp(color, 0.0, 1.0);


    float fog;
    fog = (gl_Fog.end - gl_FogFragCoord) * gl_Fog.scale;
    fog = clamp(fog, 0.0, 1.0);

    color = vec4(mix( vec3(gl_Fog.color), vec3(color), fog), color.a);

    gl_FragColor = color;
}
